### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by ArjixWasTaken** [ScaryUnicorn/Daijobu-Modules#1]
Why javascript in json?
Thats literally the worst idea, if you can execute code that is within json files, then you surely can execute js files.

Which makes it a million times better than executing code from json files....

**Comment by ArjixWasTaken** [comment]
I guess you got inspired by Orion or something, he did this exact thing with one of his apps.

**Comment by ArjixWasTaken** [comment]
The only upside I can consider is that you are limiting what a module can do, so third party modules don't have a lot of freedom, that is of course if you don't execute code without safety checks

**Comment by ScaryUnicorn** [comment]
@ArjixWasTaken I don't see any js in any of the json files. Please enlighten me where you see js. getElement and getJSON are all placeholder values and can never be executed. Unlike other apps, daijobu is not written with js and thus cannot execute js, so even if that json files had a billion lines of malicious js code, the app still wouldn't execute them, since it doesn't know how to.

**Comment by ScaryUnicorn** [comment]
Nah it's all good. I am using json since I don't plan on creating a lot of modules myself, so json is somewhat an obvious choice. It's easy to understand and anyone can watch a 10 min YouTube video and start creating modules.
